# Generated by Django 3.0.6 on 2020-05-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='balance',
        ),
    ]
