# Generated by Django 3.0.6 on 2020-07-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0003_auto_20200527_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
