# Generated by Django 3.0.6 on 2020-07-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0005_cuenta_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='key',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='contable.Categoria'),
            preserve_default=False,
        ),
    ]
