# Generated by Django 3.0.6 on 2020-07-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0007_auto_20200716_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='key',
        ),
    ]
