# Generated by Django 3.0.8 on 2020-07-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0008_auto_20200716_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tipo',
            new_name='modo',
        ),
    ]
