# Generated by Django 3.0.8 on 2020-07-19 16:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0009_auto_20200719_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
