# Generated by Django 3.0.8 on 2020-09-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0010_auto_20200719_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='color',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='key',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subticket',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contable.Proyecto'),
        ),
    ]
