# Generated by Django 3.0.8 on 2020-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0011_auto_20200922_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='key',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
