# Generated by Django 3.0.8 on 2020-09-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0012_auto_20200922_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subticket',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='ticket',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contable.Proyecto'),
        ),
    ]
