# Generated by Django 3.0.8 on 2020-09-22 17:46

import contable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0013_auto_20200922_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(on_delete=models.SET(contable.models.get_uncategorized), to='contable.Categoria'),
        ),
    ]
