# Generated by Django 3.1.4 on 2020-12-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0021_auto_20201229_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gasto',
            field=models.CharField(choices=[('D', 'Discrecional'), ('F', 'Fijo')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=8)),
                ('value', models.FloatField()),
                ('amount', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contable.ticket')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contable.moneda')),
            ],
        ),
    ]
