# Generated by Django 3.1.4 on 2020-12-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0022_auto_20201230_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gasto',
            field=models.CharField(choices=[('D', 'Discrecional'), ('V', 'Variable'), ('F', 'Fijo'), ('I', 'Inversion')], max_length=1),
        ),
    ]
