# Generated by Django 3.1.4 on 2020-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0023_auto_20201230_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tax',
            field=models.CharField(blank=True, choices=[('IRPF', 'IRPF'), (None, 'None')], max_length=4, null=True),
            preserve_default=True,
        ),
    ]
