# Generated by Django 3.1.4 on 2021-01-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0026_auto_20210113_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='compra',
            new_name='ticket',
        ),
    ]
