# Generated by Django 3.1.4 on 2021-01-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0027_auto_20210113_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='value',
            new_name='unitvalue',
        ),
    ]
