# Generated by Django 3.1.4 on 2021-01-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0028_auto_20210116_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='activo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contable.activo'),
        ),
    ]
