# Generated by Django 3.1.4 on 2021-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0029_auto_20210116_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('S', 'Sold'), ('A', 'Active')], default='A', max_length=1),
        ),
    ]
